# ./docker-compose.yml
version: "3.7"
volumes:
  bundle:
    driver: local
  mysql:
    driver: local
  tmp:
    driver: local
  node-modules:
    driver: local

x-common-environment: &common-environment
  RAILS_ENV: "development"
  MYSQL_HOST: "mysql"
  MYSQL_USER: "root"
  MYSQL_PORT: "3306"
  MYSQL_PASSWORD: "root"
  BUNDLE_PATH: "/bundle"
  BUNDLE_JOBS: "2"
  BUNDLE_RETRY: "3"
  BASE_URL: "http://localhost"
  BASE_URL_PORT: "5555"
  SESSION_TIMEOUT_IN_SECONDS: "900"
  SESSION_TIMEOUT_WARNING: "true"
  RAILS_MAX_THREADS: "1"
  REDIS_URL: "redis://redis"
  BUNDLER_RAILS_VERSION: "~> 6.0.0"

services:
  mysql:
    image: mysql:8.0.21
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=mysql
    ports:
      - "3308:3306"
    expose:
      - "3308"
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    expose:
      - 6379
  engine:
    build:
      args:
        BUNDLE_WITHOUT: "darwin"
        RAILS_ENV: development
      target: base
      context: .
    command: test/dummy/bin/rails s -p 5555 -e development -b '0.0.0.0'
    # so things like pry work
    tty: true
    stdin_open: true
    volumes:
      - .:/home/app
      - bundle:/bundle
      - node-modules:/home/app/node_modules
      - tmp:/home/app/tmp
      - ..:/local
    env_file:
      - .env
    environment:
      <<: *common-environment
    ports:
      - "5555:5555"
    links:
      - mysql
      - redis
  engine_with_sidekiq:
    build:
      args:
        BUNDLE_WITHOUT: "darwin"
        RAILS_ENV: development
      target: base
      context: .
    command: test/dummy/bin/rails s -p 5555 -e development -b '0.0.0.0'
    # so things like pry work
    tty: true
    stdin_open: true
    volumes:
      - .:/home/app
      - bundle:/bundle
      - node-modules:/home/app/node_modules
      - tmp:/home/app/tmp
      - ..:/local
    env_file:
      - .env
    environment:
      <<: *common-environment
      USE_SIDEKIQ: "true"
    ports:
      - "5555:5555"
    links:
      - mysql
      - redis
      - sidekiq
  sidekiq:
    build:
      args:
        BUNDLE_WITHOUT: "darwin"
        RAILS_ENV: development
      target: base
      context: .
    command: test/dummy/bin/sidekiq -e development -q twilio_sms,1 -q default,1 -q mailers,1
    # so things like pry work
    tty: true
    stdin_open: true
    volumes:
      - .:/home/app
      - bundle:/bundle
      - node-modules:/home/app/node_modules
      - tmp:/home/app/tmp
      - ..:/local
    env_file:
      - .env
    environment:
      <<: *common-environment
    links:
      - mysql
      - redis

